# Generated by Django 5.0 on 2024-01-03 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=20)),
                ('relaease_date', models.DateField(default=django.utils.timezone.now)),
                ('musician', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='musicians.musician')),
            ],
        ),
    ]
